# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Sucias are My Favorite
logo: /images/masthead.png
masthead_title: are my Favorite
email: el.gallo.cochino@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  'Life dating and relationship advice with a kink twist, life experiences, and personal stories'
github_username: gChingon
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Outputting
future: false
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Americas/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _blog
  - _feat

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - org/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name   : "Gallo Chingon"
  avatar : "/images/bio-photo.png"
  bio    : "A former sex addict's life experiences so you don't have to fuck yours up."
  links:
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://youtube.com/channel/UCgYSjBmIL3nkxBon4f0Gl_Q"
    - label: "Reddit"
      icon: "fab fa-reddit"
      url: "https://reddit.com/u/suciasaremyfavorite"
    - label: "Contact"
      icon: "fas fa-fw fa-envelope-square"
      url: "https://sucias.xyz/contact"

footer:
  links:
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://youtube.com/channel/UCgYSjBmIL3nkxBon4f0Gl_Q"
    - label: "TikTok"
      icon: "fab fa-tiktok"
      url: "https://tiktok.com/@sucias.are.my.favorite"
    - label: "Reddit"
      icon: "fab fa-square-reddit"
      url: "https://reddit.com/u/suciasaremyfavorite"

collections:
  feat:
    output: true
    permalink: /:collection/:path/
  blog:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      share: true
      related: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  # _feat
  - scope:
      path: "_feat"
      type: feat
    values:
      layout: archive
      entries_layout: grid
      author_profile: false
  # _blog
  - scope:
      path: "_blog"
      type: archive
    values:
      layout: archive
      entries_layout: grid
      author_profile: false

category_archive:
  type: liquid
  path: /categories/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-108314831-1"
    anonymize_ip: false
